#!/bin/sh
rm -f /etc/dnsgate/cache/*
COLUMNS=108; LINES=90; export COLUMNS LINES;
script -q -c ./generate_readme |\
    ./strip_ansi.pl |\
    sed -e 's/xn--n3h.net/☃.net/g' |\
    sed -e 's/* Stopping dnsmasq .../* Stopping dnsmasq ... \[ ok \]/g' |\
    sed -e 's/* Starting dnsmasq .../* Starting dnsmasq ... \[ ok \]/g' |\
    sed -e 's/dnsgate.py/dnsgate/g' |\
    sed '/^ \[ ok \]/ d' > README.md.new 2>&1
kdiff3 ../README.md README.md.new

